# Generated by Django 3.1.1 on 2020-09-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Charpter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reader.manga')),
            ],
        ),
    ]
