# Generated by Django 3.1.1 on 2020-09-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charpter',
            new_name='Chapter',
        ),
    ]
