# Generated by Django 3.1.1 on 2020-09-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='bgmId',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='dmzjId',
        ),
        migrations.AddField(
            model_name='manga',
            name='bgm_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='manga',
            name='dmzj_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='API.manga'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.chapter'),
        ),
        migrations.AlterField(
            model_name='image',
            name='fileName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manga',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mangas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='API.manga')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='API.volume'),
        ),
        migrations.AddField(
            model_name='manga',
            name='magazine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangas', to='API.magazine'),
        ),
    ]
