# Generated by Django 3.1.1 on 2020-09-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200915_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='bgmId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='dmzjId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.chapter')),
            ],
        ),
    ]
